<!DOCTYPE html>
<html lang="en-US">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="author" content="Ahmed Elsayes" />
    
    <link rel="shortcut icon" type="image/x-icon" href="../../img/favicon.ico">
    <title>Project 2: Modeling, Testing, and Predicting</title>
    <meta name="generator" content="Hugo 0.79.0" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="../../css/main.css" />
    <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" />
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:200,400,200bold,400old" />
    
    <!--[if lt IE 9]>
			<script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
			<script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
		<![endif]-->

    
  </head>

  <body>
    <div id="wrap">
      
      <nav class="navbar navbar-default">
  <div class="container">
    <div class="navbar-header">
      <a class="navbar-brand" href="../../"><i class="fa fa-home"></i></a>
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
    <div class="navbar-collapse collapse" id="navbar">
      <ul class="nav navbar-nav navbar-right">
      
        
        <li><a href="../../post/">BLOG</a></li>
        
        <li><a href="../../projects/">PROJECTS</a></li>
        
        <li><a href="../../resume/">RESUME</a></li>
        
      
      </ul>
    </div>
  </div>
</nav>

      <div class="container">
        <div class="blog-post">
          <h3>
            <strong><a href="../../project/project2/">Project 2: Modeling, Testing, and Predicting</a></strong>
          </h3>
        </div>
 
<div class="blog-title">
          <h4>
         January 1, 0001 
            &nbsp;&nbsp;
            
          </h4>
        </div>

        <div class="panel panel-default">
          <div class="panel-body">
            <div class="blogpost">
              


<div id="ahmed-elsayes-ake495" class="section level2">
<h2>Ahmed Elsayes (AKE495)</h2>
<pre class="r"><code>library(readr)
LifeExpectancy &lt;- read_csv(&quot;Life Expectancy Data.csv&quot;)
names(LifeExpectancy)[4] &lt;- &quot;LE&quot;
names(LifeExpectancy)[5] &lt;- &quot;AM&quot;
names(LifeExpectancy)[6] &lt;- &quot;ID&quot;</code></pre>
<p><em>Introduction: This dataset shows trends of countries based on their status as either developed or developing. There are 26 variables of 2,938 total observations for this dataset. The reason why there are so many observations is because of the amount of countries and the number of years per country. There are too many variables in this dataset, so the ones that I will be looking at the most are country, status (developed or developing), Life expectancy, adult mortality, and infant deaths. I am eager to figure out the trends and differences in various different statistics between developing and developed countries around the world.</em></p>
<pre class="r"><code>manov &lt;-manova(cbind(LE, AM, ID, Schooling)~Status, data=LifeExpectancy)
summary(manov) #MANOVA across European soccer leagues</code></pre>
<pre><code>## Df Pillai approx F num Df den Df Pr(&gt;F)
## Status 1 0.28376 273.67 4 2763 &lt; 2.2e-16 ***
## Residuals 2766
## ---
## Signif. codes: 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1
&#39; &#39; 1</code></pre>
<pre class="r"><code>summary.aov(manov) #ANOVA</code></pre>
<pre><code>## Response LE :
## Df Sum Sq Mean Sq F value Pr(&gt;F)
## Status 1 54814 54814 808 &lt; 2.2e-16 ***
## Residuals 2766 187643 68
## ---
## Signif. codes: 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1
&#39; &#39; 1
##
## Response AM :
## Df Sum Sq Mean Sq F value Pr(&gt;F)
## Status 1 3750282 3750282 272.4 &lt; 2.2e-16 ***
## Residuals 2766 38080655 13767
## ---
## Signif. codes: 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1
&#39; &#39; 1
##
## Response ID :
## Df Sum Sq Mean Sq F value Pr(&gt;F)
## Status 1 460658 460658 32.214 1.524e-08 ***
## Residuals 2766 39553848 14300
## ---
## Signif. codes: 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1
&#39; &#39; 1
##
## Response Schooling :
## Df Sum Sq Mean Sq F value Pr(&gt;F)
## Status 1 8244.9 8244.9 1002.8 &lt; 2.2e-16 ***
## Residuals 2766 22741.8 8.2
## ---
## Signif. codes: 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1
&#39; &#39; 1
##
## 170 observations deleted due to missingness</code></pre>
<pre class="r"><code>pairwise.t.test(LifeExpectancy$LE,LifeExpectancy$Status, p.adj=&quot;none&quot;) #T-tests</code></pre>
<pre><code>## 
##  Pairwise comparisons using t tests with pooled SD 
## 
## data:  LifeExpectancy$LE and LifeExpectancy$Status 
## 
##            Developed
## Developing &lt;2e-16   
## 
## P value adjustment method: none</code></pre>
<pre class="r"><code>pairwise.t.test(LifeExpectancy$AM,LifeExpectancy$Status, p.adj=&quot;none&quot;)</code></pre>
<pre><code>## 
##  Pairwise comparisons using t tests with pooled SD 
## 
## data:  LifeExpectancy$AM and LifeExpectancy$Status 
## 
##            Developed
## Developing &lt;2e-16   
## 
## P value adjustment method: none</code></pre>
<pre class="r"><code>pairwise.t.test(LifeExpectancy$ID,LifeExpectancy$Status, p.adj=&quot;none&quot;)</code></pre>
<pre><code>## 
##  Pairwise comparisons using t tests with pooled SD 
## 
## data:  LifeExpectancy$ID and LifeExpectancy$Status 
## 
##            Developed
## Developing 1.1e-09  
## 
## P value adjustment method: none</code></pre>
<pre class="r"><code>pairwise.t.test(LifeExpectancy$Schooling,LifeExpectancy$Status, p.adj=&quot;none&quot;)</code></pre>
<pre><code>##
## Pairwise comparisons using t tests with pooled SD
##
## data: LifeExpectancy$Schooling and LifeExpectancy$Status
##
## Developed
## Developing &lt;2e-16
##
## P value adjustment method: none</code></pre>
<pre class="r"><code>1-(1-.05)^9 #chance of type 1 error</code></pre>
<pre><code>## [1] 0.3697506</code></pre>
<pre class="r"><code>0.05/9 #Bonferroni correction</code></pre>
<pre><code>## [1] 0.005555556</code></pre>
<p><em>Overall, 1 MANOVA, 4 ANOVAS, and 4 t-tests were done for a total of 9 tests. I calculated the chances of type 1 error and figured there is 0.3698 chance of a type 1 error occurring. I also adjusted the significance level using the Bonferroni Correction to a value of 0.0056. Additionally, I found a few main findings using the Bonferroni corrected significance level. I found that the there is a significant difference in life expectancy, adult mortality, schooling, and infant deaths between developing and developed countries. Lastly, there are many MANOVA test assumptions including large sample size, independent observations, multivariate normality, homogeneity of variances, etc. The likelihood of all MANOVA assumptions to be met is very low due to the multifaceted complexity of these assumptions.</em></p>
<pre class="r"><code>library(Hmisc)
library(plyr)
#randomization
LifeExpectancy &lt;- na.omit(LifeExpectancy)
summary(aov(LE~Status,data=LifeExpectancy))</code></pre>
<pre><code>## Df Sum Sq Mean Sq F value Pr(&gt;F)
## Status 1 25005 25005 401.7 &lt;2e-16 ***
## Residuals 1647 102525 62
## ---
## Signif. codes: 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1
&#39; &#39; 1</code></pre>
<pre class="r"><code>obs_F&lt;- 401.7
Fs&lt;-replicate(5000,{ 
  new &lt;- LifeExpectancy %&gt;% mutate(LE=sample(LE))
  SSW &lt;- new %&gt;% group_by(Status) %&gt;% summarize(SSW=sum((LE-mean(LE))^2)) %&gt;%       summarize(sum(SSW)) %&gt;% pull
  SSB &lt;- new %&gt;% mutate(mean=mean(LE)) %&gt;% group_by(Status) %&gt;% mutate(groupmean=mean(LE)) %&gt;% summarize(SSB=sum((mean-groupmean)^2)) %&gt;% summarize(sum(SSB)) %&gt;% pull
  (SSB/1)/(SSW/1647)
})
mean(Fs&gt;obs_F)</code></pre>
<pre><code>## [1] 0</code></pre>
<pre class="r"><code>hist(Fs, prob=T); abline(v = obs_F, col=&quot;red&quot;,add=T)</code></pre>
<p><img src="../../project/Project2_files/figure-html/unnamed-chunk-3-1.png" width="768" style="display: block; margin: auto;" /> <em>Null: Life Expectancy of developed countries does not differ from life expectancy of devloping countries. Alternative Hypothesis: Life expectancy of developed countries differs from life expectancy of devloping countries. Since the p-value is 0 which is less than 0.05, we may reject the null hypothesis and conclude that life expectancy of developed and developing countries differ significantly.</em></p>
<pre class="r"><code>library(ggplot2)
#mean centering
LE2 &lt;- LifeExpectancy %&gt;% mutate(LE = LE - mean(LE, na.rm = T))
LE2 &lt;- LifeExpectancy %&gt;% mutate(AM = AM - mean(AM, na.rm = T))
LE2 &lt;- LifeExpectancy %&gt;% mutate(ID = ID - mean(ID, na.rm = T))
LE2 &lt;- LifeExpectancy %&gt;% mutate(Schooling = Schooling - mean(Schooling, na.rm = T))
LE2 &lt;- LifeExpectancy %&gt;% mutate(Status=ifelse(Status==&quot;Developed&quot;,1,0))
#linear regression
Regr &lt;- lm(Schooling~LE*Status, data = LE2)
summary(Regr)</code></pre>
<pre><code>##
## Call:
## lm(formula = Schooling ~ LE * Status, data = LE2)
##
## Residuals:
## Min 1Q Median 3Q Max
## -6.4886 -1.0695 0.0116 1.1314 4.7486
##
## Coefficients:
## Estimate Std. Error t value Pr(&gt;|t|)
## (Intercept) -2.02365 0.39693 -5.098 3.82e-07 ***
## LE 0.20018 0.00582 34.395 &lt; 2e-16 ***
## Status 6.01298 2.20171 2.731 0.00638 **
## LE:Status -0.05297 0.02809 -1.886 0.05952 .
## ---
## Signif. codes: 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1
&#39; &#39; 1
##
## Residual standard error: 1.823 on 1645 degrees of
freedom
## Multiple R-squared: 0.5754, Adjusted R-squared: 0.5747
## F-statistic: 743.2 on 3 and 1645 DF, p-value: &lt; 2.2e-16</code></pre>
<pre class="r"><code>#regression ggplot
ggplot(LE2, aes(x = LE, y = Schooling, group = Status)) + geom_point(aes(color=Status)) +
geom_smooth(method=&quot;lm&quot;, se=F,fullrange=T,aes(color=Status)) </code></pre>
<p><img src="../../project/Project2_files/figure-html/unnamed-chunk-4-1.png" width="768" style="display: block; margin: auto;" /></p>
<pre class="r"><code>#assumptions
residuals &lt;- Regr$residuals
fitted &lt;- Regr$fitted.values
ggplot(data.frame(fitted,residuals), aes(fitted,residuals)) + geom_point() + geom_hline(yintercept=0, color=&#39;red&#39;)</code></pre>
<p><img src="../../project/Project2_files/figure-html/unnamed-chunk-4-2.png" width="768" style="display: block; margin: auto;" /></p>
<pre class="r"><code>ggplot() + geom_histogram(aes(residuals), bins=50)</code></pre>
<p><img src="../../project/Project2_files/figure-html/unnamed-chunk-4-3.png" width="768" style="display: block; margin: auto;" /></p>
<pre class="r"><code>ggplot() + geom_qq(aes(sample=residuals)) + geom_qq_line(aes(sample=residuals, color=&#39;red&#39;)) + theme(legend.position = &quot;none&quot;)</code></pre>
<p><img src="../../project/Project2_files/figure-html/unnamed-chunk-4-4.png" width="768" style="display: block; margin: auto;" /></p>
<pre class="r"><code>#SE
library(lmtest)
library(sandwich)
coeftest(Regr)</code></pre>
<pre><code>##
## t test of coefficients:
##
## Estimate Std. Error t value Pr(&gt;|t|)
## (Intercept) -2.023654 0.396929 -5.0983 3.823e-07 ***
## LE 0.200178 0.005820 34.3947 &lt; 2.2e-16 ***
## Status 6.012976 2.201714 2.7310 0.006381 **
## LE:Status -0.052968 0.028090 -1.8857 0.059516 .
## ---
## Signif. codes: 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1
&#39; &#39; 1</code></pre>
<pre class="r"><code>coeftest(Regr, vcov = vcovHC(Regr)) #robust</code></pre>
<pre><code>##
## t test of coefficients:
##
## Estimate Std. Error t value Pr(&gt;|t|)
## (Intercept) -2.0236541 0.4702893 -4.3030 1.784e-05 ***
## LE 0.2001781 0.0066794 29.9697 &lt; 2.2e-16 ***
## Status 6.0129756 1.8502868 3.2498 0.001178 **
## LE:Status -0.0529678 0.0240325 -2.2040 0.027662 *
## ---
## Signif. codes: 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1
&#39; &#39; 1</code></pre>
<pre class="r"><code>Regr2 &lt;- lm(Schooling~LE + Status, data = LE2)
summary(Regr2)</code></pre>
<pre><code>##
## Call:
## lm(formula = Schooling ~ LE + Status, data = LE2)
##
## Residuals:
## Min 1Q Median 3Q Max
## -6.4856 -1.0555 0.0103 1.1341 4.6873
##
## Coefficients:
## Estimate Std. Error t value Pr(&gt;|t|)
## (Intercept) -1.869742 0.388747 -4.81 1.65e-06 ***
## LE 0.197904 0.005698 34.73 &lt; 2e-16 ***
## Status 1.869868 0.141610 13.20 &lt; 2e-16 ***
## ---
## Signif. codes: 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1
&#39; &#39; 1
##
## Residual standard error: 1.825 on 1646 degrees of
freedom
## Multiple R-squared: 0.5745, Adjusted R-squared: 0.574
## F-statistic: 1111 on 2 and 1646 DF, p-value: &lt; 2.2e-16</code></pre>
<pre class="r"><code>lrtest(Regr, Regr2)</code></pre>
<pre><code>## Likelihood ratio test
##
## Model 1: Schooling ~ LE * Status
## Model 2: Schooling ~ LE + Status
## #Df LogLik Df Chisq Pr(&gt;Chisq)
## 1 5 -3328.1
## 2 4 -3329.9 -1 3.5605 0.05917 .
## ---
## Signif. codes: 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1
&#39; &#39; 1</code></pre>
<p><em>I obtained many coefficients using the linear regression. For countries with average life expectancy, schooling is 2.02 less in developing countries than developed countries. While controlling for country status, for every year increase in Life Expectancy, schooling increases by about a rating of 0.2. Additionally, controlling for life expectancy, there is a 6.01 difference in schooling between developed and developing countries. Also, there was no significant observable changes between the regular standard error and the robust standard error because the significance level did not change for any of the variables. Lastly, using the r-squared value, I know that my model explains 57.47 percent of the variation in the outcome.</em></p>
<pre class="r"><code>#bootstrapped SE
bootstrap &lt;- replicate(5000, {
databootstrap &lt;- sample_frac(LE2, replace = T)
fit&lt;-lm(Schooling~LE*Status, data = databootstrap)
coef(fit)
})</code></pre>
<p><em>When SE increases, the t decreases and p values increase. In the bootstrapped standard errors the intercept SE increased, the life expectancy SE decreased, and the status SE decreased. Also, these same trends hold true for the robust SEs as well. With this being said, the t-value decreased for the intercept, increased for life expectancy, and increased for status between bootstrap SE and normal or robust SEs. Lastly, the p-value increase for the intercept, decreased for life expectancy, and decreases for status between bootstrap SE and normal or robust SEs.</em></p>
<pre class="r"><code>#logistic regression
logreg &lt;- glm(Status~Schooling + LE +AM, data = LE2, family=&quot;binomial&quot;)
coeftest(logreg)</code></pre>
<pre><code>##
## z test of coefficients:
##
## Estimate Std. Error z value Pr(&gt;|z|)
## (Intercept) -21.8438851 1.9980853 -10.9324 &lt; 2.2e-16 ***
## Schooling 0.6620635 0.0678865 9.7525 &lt; 2.2e-16 ***
## LE 0.1507742 0.0277663 5.4301 5.631e-08 ***
## AM -0.0023316 0.0017169 -1.3581 0.1744
## ---
## Signif. codes: 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1
&#39; &#39; 1</code></pre>
<pre class="r"><code>exp(coef(logreg)) %&gt;% data.frame()</code></pre>
<pre><code>##                        .
## (Intercept) 3.260778e-10
## Schooling   1.938789e+00
## LE          1.162734e+00
## AM          9.976711e-01</code></pre>
<pre class="r"><code>#confusion matrix
confusion &lt;- predict(logreg, type = &quot;response&quot;)
table(truth=LE2$Status,predict=as.numeric(confusion&gt;.5)) %&gt;% addmargins</code></pre>
<pre><code>##      predict
## truth    0    1  Sum
##   0   1338   69 1407
##   1    127  115  242
##   Sum 1465  184 1649</code></pre>
<pre class="r"><code>#Accuracy
#Sensitivity(TPR)
#Specificity (TNR)
#Precision (PPV)</code></pre>
<pre class="r"><code>#Density  log-odds plot
LE2$logit &lt;- predict(logreg)
ggplot(LE2, aes(logit, fill=Status)) + geom_density(alpha=0.3) + geom_vline(xintercept=0, lty=2)</code></pre>
<p><img src="../../project/Project2_files/figure-html/unnamed-chunk-8-1.png" width="768" style="display: block; margin: auto;" /></p>
<pre class="r"><code>#LASSO regression
library(glmnet)
lasso &lt;- glm(Status ~ -1 + LE + AM + ID + Schooling, data = LE2, family = &quot;binomial&quot;)
y &lt;- as.matrix(LE2$Status)
x &lt;- model.matrix(lasso)
x &lt;- scale(x)
cv &lt;- cv.glmnet(x,y, family=&#39;binomial&#39;)
lasso2 &lt;- glmnet(x,y,family=&quot;binomial&quot;,lambda=cv$lambda.1se)
coef(cv)</code></pre>
<pre><code>## 5 x 1 sparse Matrix of class &quot;dgCMatrix&quot;
##                      1
## (Intercept) -5.7838642
## LE           1.1900592
## AM          -0.2217031
## ID          -9.2246578
## Schooling    1.7230571</code></pre>
<pre class="r"><code>probab &lt;- predict(lasso, type=&quot;response&quot;)</code></pre>
<pre class="r"><code>#10-fold CV
set.seed(1234)
k=10

data10 &lt;- LE2[sample(nrow(LE2)),]</code></pre>
</div>
<div id="modeling" class="section level1">
<h1>Modeling</h1>
<div id="instructions" class="section level2">
<h2>Instructions</h2>
<p>A knitted R Markdown document (preferably HTML) and the raw R Markdown file (as .Rmd) should both be submitted to Canvas by 11:59pm on the due date. These two documents will be graded jointly, so they must be consistent (i.e., don’t change the R Markdown file without also updating the knitted document). Knit an html copy too, for later! In the .Rmd file for Project 2, you can copy the first code-chunk into your project .Rmd file to get better formatting. Notice that you can adjust the opts_chunk$set(...) above to set certain parameters if necessary to make the knitting cleaner (you can globally set the size of all plots, etc). You can copy the set-up chunk in Project2.Rmd: I have gone ahead and set a few for you (such as disabling warnings and package-loading messges when knitting)!</p>
<p>Like before, I envision your written text forming something of a narrative structure around your code/output. All results presented must have corresponding code. Any answers/results/plots etc. given without the corresponding R code that generated the result will not be graded. Furthermore, all code contained in our project document should work properly. Please do not include any extraneous code or code which produces error messages. (Code which produces warnings is fine as long as you understand what the warnings mean.)</p>
</div>
<div id="find-data" class="section level2">
<h2>Find data:</h2>
<p>Find one dataset with at least 5 variables (ideally more!) that you want to use to build models/test hypotheses. At least one should be categorical (with 2-5 groups, ideally; definitely fewer than 10) and at least two should be numeric (taking on more than 10 distinct values). Ideally, at least of your variables will be binary (if not, you will have to create one by discretizing a numeric or collapsing levels of a categorical). You will need a minimum of 40 observations (<em>at least</em> 10 observations for every explanatory variable you have, ideally 20+ observations/variable).</p>
<p>It is perfectly fine to use either dataset (or the merged dataset, or a subset of your variables) from Project 1. However, I might encourage you to diversify things a bit and choose a different dataset to work with (particularly if the variables did not reveal interesting associations in Project 1 that you want to follow up with). The only requirement/restriction is that you may not use data from any examples we have done in class or lab. It would be a good idea to pick more cohesive data this time around (i.e., variables that you actually thing might have a relationship you would want to test). Think more along the lines of your Biostats project.</p>
<p>Again, you can use data from anywhere you want (see bottom for resources)! If you want a quick way to see whether a built-in (R) dataset has binary and/or character (i.e., categorical) variables, check out this list: <a href="https://vincentarelbundock.github.io/Rdatasets/datasets.html" class="uri">https://vincentarelbundock.github.io/Rdatasets/datasets.html</a>.</p>
</div>
<div id="guidelines-and-rubric" class="section level2">
<h2>Guidelines and Rubric</h2>
<ul>
<li><p><strong>0. (5 pts)</strong> Introduce your dataset and each of your variables (or just your main variables if you have lots) in a paragraph. What are they measuring? How many observations?</p></li>
<li><p><strong>1. (15 pts)</strong> Perform a MANOVA testing whether any of your numeric variables (or a subset of them, if including them all is unreasonable or doesn't make sense) show a mean difference across levels of one of your categorical variables (3). If they do, perform univariate ANOVAs to find response(s) showing a mean difference across groups (3), and perform post-hoc t tests to find which groups differ (3). Discuss the number of tests you have performed, calculate the probability of at least one type I error (if unadjusted), and adjust the significance level accordingly (bonferroni correction) before discussing significant differences (3). Briefly discuss MANOVA assumptions and whether or not they are likely to have been met (no need for anything too in-depth) (2).</p></li>
<li><p><strong>2. (10 pts)</strong> Perform some kind of randomization test on your data (that makes sense). The statistic can be anything you want (mean difference, correlation, F-statistic/ANOVA, chi-squared), etc. State null and alternative hypotheses, perform the test, and interpret the results (7). Create a plot visualizing the null distribution and the test statistic (3).</p></li>
<li><p><strong>3. (35 pts)</strong> Build a linear regression model predicting one of your response variables from at least 2 other variables, including their interaction. Mean-center any numeric variables involved in the interaction.</p>
<ul>
<li>Interpret the coefficient estimates (do not discuss significance) (10)</li>
<li>Plot the regression using <code>ggplot()</code> using geom_smooth(method=&quot;lm&quot;). If your interaction is numeric by numeric, refer to code in the slides to make the plot or check out the <code>interactions</code> package, which makes this easier. If you have 3 or more predictors, just chose two of them to plot for convenience. (8)</li>
<li>Check assumptions of linearity, normality, and homoskedasticity either graphically or using a hypothesis test (4)</li>
<li>Regardless, recompute regression results with robust standard errors via <code>coeftest(..., vcov=vcovHC(...))</code>. Discuss significance of results, including any changes from before/after robust SEs if applicable. (8)</li>
<li>What proportion of the variation in the outcome does your model explain? (4)</li>
</ul></li>
<li><p><strong>4. (5 pts)</strong> Rerun same regression model (with the interaction), but this time compute bootstrapped standard errors (either by resampling observations or residuals). Discuss any changes you observe in SEs and p-values using these SEs compared to the original SEs and the robust SEs)</p></li>
<li><p><strong>5. (25 pts)</strong> Fit a logistic regression model predicting a binary variable (if you don't have one, make/get one) from at least two explanatory variables (interaction not necessary).</p>
<ul>
<li>Interpret coefficient estimates in context (10)</li>
<li>Report a confusion matrix for your logistic regression (2)</li>
<li>Compute and discuss the Accuracy, Sensitivity (TPR), Specificity (TNR), Precision (PPV), and AUC of your model (5)</li>
<li>Using ggplot, make a density plot of the log-odds (logit) colored/grouped by your binary outcome variable (3)</li>
<li>Generate an ROC curve (plot) and calculate AUC (either manually or with a package); interpret (5)</li>
</ul></li>
<li><p><strong>6. (25 pts)</strong> Perform a logistic regression predicting the same binary response variable from <em>ALL</em> of the rest of your variables (the more, the better!)</p>
<ul>
<li>Fit model, compute in-sample classification diagnostics (Accuracy, Sensitivity, Specificity, Precision, AUC), and interpret (5)</li>
<li>Perform 10-fold (or repeated random sub-sampling) CV with the same model and report average out-of-sample classification diagnostics (Accuracy, Sensitivity, Specificity, Precision, and AUC); interpret AUC and compare with the in-sample metrics (10)</li>
<li>Perform LASSO on the same model/variables. Choose lambda to give the simplest model whose accuracy is near that of the best (i.e., <code>lambda.1se</code>). Discuss which variables are retained. (5)</li>
<li>Perform 10-fold CV using only the variables lasso selected: compare model's out-of-sample AUC to that of your logistic regressions above (5)</li>
</ul></li>
</ul>
</div>
<div id="where-do-i-find-data-again" class="section level2">
<h2>Where do I find data again?</h2>
<p>You can choose ANY datasets you want that meet the above criteria for variables and observations. You can make it as serious as you want, or not, but keep in mind that you will be incorporating this project into a portfolio webpage for your final in this course, so choose something that really reflects who you are, or something that you feel will advance you in the direction you hope to move career-wise, or something that you think is really neat, or whatever. On the flip side, regardless of what you pick, you will be performing all the same tasks, so it doesn't end up being that big of a deal.</p>
<p>If you are totally clueless and have no direction at all, log into the server and type</p>
<pre class="r"><code>data(package = .packages(all.available = TRUE))</code></pre>
<p>This will print out a list of <strong>ALL datasets in ALL packages</strong> installed on the server (a ton)! Scroll until your eyes bleed! Actually, do not scroll that much... To start with something more manageable, just run the command on your own computer, or just run <code>data()</code> to bring up the datasets in your current environment. To read more about a dataset, do <code>?packagename::datasetname</code>.</p>
<p>If it is easier for you, and in case you don't have many packages installed, a list of R datasets from a few common packages (also downloadable in CSV format) is given at the following website: <a href="https://vincentarelbundock.github.io/Rdatasets/datasets.html" class="uri">https://vincentarelbundock.github.io/Rdatasets/datasets.html</a>.</p>
<ul>
<li><p>A good package to download for fun/relevant data is <code>fivethiryeight</code>. Run <code>install.packages(&quot;fivethirtyeight&quot;),</code> load the packages with <code>library(fivethirtyeight)</code>, run <code>data()</code>, and then scroll down to view the datasets. Here is an online list of all 127 datasets (with links to the 538 articles). Lots of sports, politics, current events, etc.</p></li>
<li><p>If you have already started to specialize (e.g., ecology, epidemiology) you might look at discipline-specific R packages (vegan, epi, respectively). We will be using some tools from these packages later in the course, but they come with lots of data too, which you can explore according to the directions above</p></li>
<li><p>However, you <em>emphatically DO NOT</em> have to use datasets available via R packages! In fact, I would much prefer it if you found the data from completely separate sources and brought them together (a much more realistic experience in the real world)! You can even reuse data from your SDS328M project, provided it shares a variable in common with other data which allows you to merge the two together (e.g., if you still had the timestamp, you could look up the weather that day: <a href="https://www.wunderground.com/history/" class="uri">https://www.wunderground.com/history/</a>). If you work in a research lab or have access to old data, you could potentially merge it with new data from your lab!</p></li>
<li><p>Here is a curated list of interesting datasets (read-only spreadsheet format): <a href="https://docs.google.com/spreadsheets/d/1wZhPLMCHKJvwOkP4juclhjFgqIY8fQFMemwKL2c64vk/edit" class="uri">https://docs.google.com/spreadsheets/d/1wZhPLMCHKJvwOkP4juclhjFgqIY8fQFMemwKL2c64vk/edit</a></p></li>
<li><p>Here is another great compilation of datasets: <a href="https://github.com/rfordatascience/tidytuesday" class="uri">https://github.com/rfordatascience/tidytuesday</a></p></li>
<li><p>Here is the UCI Machine Learning Repository: <a href="https://archive.ics.uci.edu/ml/index.php" class="uri">https://archive.ics.uci.edu/ml/index.php</a></p>
<ul>
<li>See also <a href="https://en.wikipedia.org/wiki/List_of_datasets_for_machine-learning_research#Biological_data" class="uri">https://en.wikipedia.org/wiki/List_of_datasets_for_machine-learning_research#Biological_data</a></li>
</ul></li>
<li><p>Here is another good general place to look: <a href="https://www.kaggle.com/datasets" class="uri">https://www.kaggle.com/datasets</a></p></li>
<li><p>To help narrow your search down or to see interesting variable ideas, check out <a href="https://www.tylervigen.com/spurious-correlations" class="uri">https://www.tylervigen.com/spurious-correlations</a>. This is the spurious correlations website, and it is fun, but if you look at the bottom of each plot you will see sources for the data. This is a good place to find very general data (or at least get a sense of where you can scrape data together from)!</p></li>
<li><p>If you are interested in medical data, check out www.countyhealthrankings.org</p></li>
<li><p>If you are interested in scraping UT data, they make <em>loads</em> of data public (e.g., beyond just professor CVs and syllabi). Check out all the data that is available in the statistical handbooks: <a href="https://reports.utexas.edu/statistical-handbook" class="uri">https://reports.utexas.edu/statistical-handbook</a></p></li>
</ul>
<div id="broader-data-sources" class="section level5">
<h5>Broader data sources:</h5>
<p><a href="www.data.gov">Data.gov</a> 186,000+ datasets!</p>
<p><a href="Social%20Explorer">Social Explorer</a> is a nice interface to Census and American Community Survey data (more user-friendly than the government sites). May need to sign up for a free trial.</p>
<p><a href="www.bls.gov">U.S. Bureau of Labor Statistics</a></p>
<p><a href="www.census.gov">U.S. Census Bureau</a></p>
<p><a href="www.gapminder.org/data">Gapminder</a>, data about the world.</p>
<p>...</p>
</div>
</div>
</div>

            
        <hr>         <div class="related-posts">
                <h5>Related Posts</h5>
                
              </div> 
            </div>
          </div>

   <hr>  <div class="disqus">
  <div id="disqus_thread"></div>
  <script type="text/javascript">

    (function() {
      
      
      if (window.location.hostname == "localhost")
        return;

      var disqus_shortname = '';
      var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
      dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
      (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
    })();
  </script>
  <noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
  <a href="http://disqus.com/" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a>
</div> 
        </div>
      </div>
    </div>

    
    <footer>
  <div id="footer">
    <div class="container">
      <p class="text-muted">&copy; All rights reserved. Powered by <a href="https://gohugo.io/">Hugo</a> and
      <a href="http://www.github.com/nurlansu/hugo-sustain/">sustain</a> with ♥</p>
    </div>
  </div>
</footer>
<div class="footer"></div>


<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>

<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<script src="../../js/docs.min.js"></script>
<script src="../../js/main.js"></script>

<script src="../../js/ie10-viewport-bug-workaround.js"></script>


    
  </body>
</html>
